package com.wonddak.loacell.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF1D5FA6)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFD4E3FF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001C3A)
internal val md_theme_light_secondary = Color(0xFF1860A5)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFD3E3FF)
internal val md_theme_light_onSecondaryContainer = Color(0xFF001C39)
internal val md_theme_light_tertiary = Color(0xFF0361A3)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFD1E4FF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF001D36)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFF8FDFF)
internal val md_theme_light_onBackground = Color(0xFF001F25)
internal val md_theme_light_surface = Color(0xFFF8FDFF)
internal val md_theme_light_onSurface = Color(0xFF001F25)
internal val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
internal val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
internal val md_theme_light_outline = Color(0xFF74777F)
internal val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
internal val md_theme_light_inverseSurface = Color(0xFF00363F)
internal val md_theme_light_inversePrimary = Color(0xFFA5C8FF)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF1D5FA6)
internal val md_theme_light_outlineVariant = Color(0xFFC3C6CF)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFFA5C8FF)
internal val md_theme_dark_onPrimary = Color(0xFF00315E)
internal val md_theme_dark_primaryContainer = Color(0xFF004785)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFD4E3FF)
internal val md_theme_dark_secondary = Color(0xFFA3C9FF)
internal val md_theme_dark_onSecondary = Color(0xFF00315C)
internal val md_theme_dark_secondaryContainer = Color(0xFF004882)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFD3E3FF)
internal val md_theme_dark_tertiary = Color(0xFF9FCAFF)
internal val md_theme_dark_onTertiary = Color(0xFF003258)
internal val md_theme_dark_tertiaryContainer = Color(0xFF00497D)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFD1E4FF)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF001F25)
internal val md_theme_dark_onBackground = Color(0xFFA6EEFF)
internal val md_theme_dark_surface = Color(0xFF001F25)
internal val md_theme_dark_onSurface = Color(0xFFA6EEFF)
internal val md_theme_dark_surfaceVariant = Color(0xFF43474E)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC3C6CF)
internal val md_theme_dark_outline = Color(0xFF8D9199)
internal val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
internal val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
internal val md_theme_dark_inversePrimary = Color(0xFF1D5FA6)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFFA5C8FF)
internal val md_theme_dark_outlineVariant = Color(0xFF43474E)
internal val md_theme_dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFF112D4E)
