target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'FirebaseFirestore', '~> 10.10.0'
  pod 'FirebaseFirestoreSwift', '~> 10.10.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1' # 원하는 최소 버전
      end
    end
end