target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'AlertToast'
  pod 'FirebaseAnalytics', '~> 10.27.0'
  pod 'FirebaseCrashlytics', '~> 10.27.0'
  pod 'GoogleSignIn', '~> 7.1'
  pod 'GoogleSignInSwiftSupport', '~> 7.1'
  pod 'KakaoSDKShare'
  pod 'composeApp', :path => '../composeApp'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.2'
  end
 end
end